name: credee-test

services:
  api:
    image: credee/api:latest
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=credee
      - DB_PASS=credee
      - DB_NAME=credee

  worker:
    image: credee/worker:latest
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: credee
      POSTGRES_USER: credee
      POSTGRES_DB: credee
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  redis:
  postgres:
