// Generated by 'unplugin-auto-import'
export {}
declare global {
  const IconPhAt: typeof import('~icons/ph/at.jsx')['default']
  const IconPhFileSearch: typeof import('~icons/ph/file-search.jsx')['default']
}
