name: Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  api:
    runs-on: ubuntu-latest
    name: Build & Publish API
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build and Publish
        uses: ./.github/actions/docker-build
        with:
          context: .
          imageTag: credee/api
          dockerfile: packages/api/Dockerfile
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  worker:
    runs-on: ubuntu-latest
    name: Build & Publish Worker
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build and Publish
        uses: ./.github/actions/docker-build
        with:
          context: .
          imageTag: credee/worker
          dockerfile: packages/worker/Dockerfile
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  www:
    runs-on: ubuntu-latest
    name: Build & Publish Web
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build and Publish
        uses: ./.github/actions/docker-build
        with:
          context: .
          imageTag: credee/www
          dockerfile: packages/www/Dockerfile
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
